### ISSUE TITLE
unexpected collapse/expand

### ISSUE THREAD

**Issue by iamyangchen** [TAMUBazinga/TA_Assignment#29]
In course#select_new_ta, any click on the checkbox, selection of position, or Detail will collapse/expand the entry.

**Comment by bovetliu** [comment]
Since current code you did not stop propagation of "click" event (when the checkbox received click event, you should immediately stop propagation of click event), you might want to refer the codes I wrote at /app/assets/javascripts/courses.js Line 9

**Comment by bovetliu** [comment]
resolved
